### ISSUE TITLE
Custom default sky

### ISSUE THREAD

**Issue by tacotexmex** [xeranas/skycolor#2]
It would be handy to have set_default_sky referring to an optional custom sky definition so that games don't have to use the "engine sky".

**Comment by rautars** [comment]
Skylayer uses layered sky approach, "engine sky" is used only if there no sky layers added/remain. Default sky in skylayer could be achieved by setting skylayer object early (e.g. when player join game) to player and don't removing later in game. See sample:

```
local default_sky_layer = {}
default_sky_layer.name = "solid_black_sky"
default_sky_layer.sky_data = {
  bgcolor = {r=0, g=0, b=0}
}

minetest.register_on_joinplayer(function(player)
	skylayer.add_layer(player:get_player_name(), default_sky_layer)
end)
```

Weather or other mods which uses skylayer will add own layers but as long as no one remove default (in sample case "solid_black_sky") after rain (or other effect) end sky should switch to previous sky layer.

**Comment by tacotexmex** [comment]
I see, this makes sense! Thank you for responding.
